# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171013_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='elemsort',
            options={'verbose_name': 'Элемент сортировки', 'verbose_name_plural': 'Элементы сортировки'},
        ),
        migrations.AlterModelOptions(
            name='sort',
            options={'verbose_name': 'Сортировка', 'verbose_name_plural': 'Сортировки'},
        ),
        migrations.AddField(
            model_name='elemsort',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
    ]
