# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171013_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemsort',
            name='sort',
        ),
        migrations.AddField(
            model_name='elemsort',
            name='sort',
            field=models.ManyToManyField(to='shop.Sort', verbose_name='Добавить в сортировку'),
        ),
    ]
