# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171013_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemsort',
            name='sort',
        ),
        migrations.AddField(
            model_name='sort',
            name='elemsort',
            field=models.ManyToManyField(to='shop.ElemSort', verbose_name='Элемент сортировки'),
        ),
    ]
