# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171013_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sort',
            name='elemsort',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sort',
        ),
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 14), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='call',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 14), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.date(2017, 10, 14), verbose_name='Дата начала акции/скидки'),
        ),
        migrations.DeleteModel(
            name='ElemSort',
        ),
        migrations.DeleteModel(
            name='Sort',
        ),
    ]
