# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20171015_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketelem',
            name='decor',
        ),
        migrations.RemoveField(
            model_name='basketelem',
            name='pack',
        ),
    ]
