# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 23:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20171015_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 19), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='basketelem',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Кол-во штук товара'),
        ),
        migrations.AlterField(
            model_name='call',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 19), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.date(2017, 10, 19), verbose_name='Дата начала акции/скидки'),
        ),
    ]
