# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 23:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20171019_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketelem',
            name='count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во штук товара'),
        ),
    ]
