# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20171019_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketelem',
            name='count',
            field=models.IntegerField(verbose_name='Кол-во штук товара'),
        ),
    ]
