# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20171019_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketelem',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Package'),
        ),
    ]
