# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_basketelem_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decorator',
        ),
        migrations.RemoveField(
            model_name='product',
            name='decor',
        ),
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 20), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='call',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 20), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.date(2017, 10, 20), verbose_name='Дата начала акции/скидки'),
        ),
    ]
