# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20171023_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_promo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.SalePromo', verbose_name='Акция/Скидка'),
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2017, 10, 24, 15, 15, 54, 813748, tzinfo=utc), verbose_name='Дата начала скидки'),
        ),
    ]
