# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20171024_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price', models.IntegerField(default=250)),
            ],
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2017, 10, 25, 11, 40, 37, 503910, tzinfo=utc), verbose_name='Дата начала скидки'),
        ),
    ]
