# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20171025_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2017, 10, 26, 10, 8, 21, 126105, tzinfo=utc), verbose_name='Дата начала скидки'),
        ),
    ]
