# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20171026_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=36, verbose_name='Идентификатор заказчика')),
                ('sum', models.IntegerField(blank=True, null=True, verbose_name='Сумма заказа, руб.')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата заказа')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя заказчика')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон заказчика')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('delivery', models.BooleanField(default=False, verbose_name='Доставка')),
                ('complite', models.BooleanField(default=False, verbose_name='Заказ оформлен')),
                ('closed', models.BooleanField(default=False, verbose_name='Заказ завершен')),
                ('count', models.IntegerField(verbose_name='Кол-во штук товара')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ в один клик',
                'verbose_name_plural': 'Заказы в один клик',
            },
        ),
        migrations.RemoveField(
            model_name='basket',
            name='delivery_sum',
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2017, 10, 28, 13, 17, 54, 294085, tzinfo=utc), verbose_name='Дата начала скидки'),
        ),
    ]
