# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20171028_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 19, 11, 51, 701309, tzinfo=utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='call',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 19, 11, 51, 699524, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='oneclick',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 19, 11, 51, 702823, tzinfo=utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2017, 10, 30, 19, 11, 51, 697704, tzinfo=utc), verbose_name='Дата начала скидки'),
        ),
    ]
