# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20171030_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(blank=True, null=True, verbose_name='Сумма заказа, руб.')),
                ('build', models.BooleanField(default=False, verbose_name='Собран')),
            ],
            options={
                'verbose_name': 'Конструктор',
                'verbose_name_plural': 'Конструкторы',
            },
        ),
        migrations.AddField(
            model_name='basketelem',
            name='constructor_child',
            field=models.BooleanField(default=False, verbose_name='товар в конструкторе'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 11, 20, 39, 256437, tzinfo=utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='basketelem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='call',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 11, 20, 39, 254652, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='oneclick',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 11, 20, 39, 258657, tzinfo=utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2017, 11, 1, 11, 20, 39, 252724, tzinfo=utc), verbose_name='Дата начала скидки'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Basket', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='basketelem',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Constructor', verbose_name='Конструктор'),
        ),
    ]
