# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20171101_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Package'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 22, 48, 4, 701778, tzinfo=utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='call',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 22, 48, 4, 699908, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='oneclick',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 22, 48, 4, 704173, tzinfo=utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='salepromo',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2017, 11, 1, 22, 48, 4, 698092, tzinfo=utc), verbose_name='Дата начала скидки'),
        ),
    ]
